FROM alpine:latest
RUN mkdir /opt/app
WORKDIR /opt/app
COPY requirements.txt requirements.txt
RUN apk update
RUN apk add python3 py3-pip git
RUN apk add bash iproute2
#RUN apk add rrdtool

# Change Shell
#RUN chsh -s /bin/bash root
RUN export SHELL="/bin/bash"
RUN ln -sf /bin/bash /bin/sh

# set ENV to execute startup scripts
ENV ENV /etc/profile

# Create venv
RUN python3 -m venv venv

# Set PATH Variable to include venv
ENV PATH="/opt/app/venv/bin:$PATH"

# Activate venv
#RUN source venv/bin/activate

# Install required Packages
RUN pip install -r requirements.txt

# Export Web Port
EXPOSE 5000

# Copy required Files
COPY app/* .
COPY README.md .

# Run the Main App
CMD ["python", "-u", "app.py"]
