# Default settings for every charger
settings:
  defaults:
    - output_voltage_volts
      - min: 48
      - max: 57
    - output_current_amperes
      - min: 5
      - max: 50

ratings:
  defaults:
    - output_voltage
      - min: 41
      - max: 58.5
    - output_current
      - min: 5.5
      - max: 62.5
    #- input_current
    #  - min: 
    #  - max: 
  R48-R3000e3:
    - output_voltage
      - min: 41
      - max: 58.5
    - output_current
      - min: 5.5
      - max: 62.5
    #- input_current
    #  - min: 
    #  - max: 

types:
  - Grid
  - Generator
  - Inverter

chargers:
  - id: 01
    enabled: true
    manufacturer: Emerson
    model: R48-3000e3
    #labels:
    #  - ...
    #  - ...
    description:
    type: Grid
    interface_type: can
    interface_name: can-grid-01
    mqtt_topic: charger-emerson-can-grid-01/
    settings:
    #  - output_voltage
    #    - min
    #    - max
      - output_current
        - min: 0.0
        - max: 50.0
      - input_current
        - min: 0.0
        - max: 13.0

  - id: 02
    enabled: true
    manufacturer: Vertiv
    model: R48-3000e3
    #labels:
    #  - ...
    #  - ...
    description:
    type: Generator
    interface_type: can
    interface_name: can-gen-01
    mqtt_topic: charger-emerson-can-gen-01/
    settings:
    #  - output_voltage
    #    - min
    #    - max
      - output_current
        - min: 0.0
        - max: 50.0
      - input_current
        - min: 0.0
        - max: 13.0
